stages:
  - build
  - push
  - deploy

# Ortak değişkenler, GitLab'da CI/CD secrets olarak tanımlanmalı
variables:
  IMAGE_BACKEND: "$ACR_LOGIN_SERVER/carrental-backend"
  IMAGE_FRONTEND: "$ACR_LOGIN_SERVER/carrental-frontend"
  IMAGE_CONVERTER: "$ACR_LOGIN_SERVER/currency-converter"

######################
# BACKEND PIPELINE
######################

build-backend:
  stage: build
  script:
    - docker build -t $IMAGE_BACKEND ./carrental
  only:
    - fati
    - main

push-backend:
  stage: push
  script:
    - echo $ACR_PASSWORD | docker login $ACR_LOGIN_SERVER -u $ACR_USERNAME --password-stdin
    - docker push $IMAGE_BACKEND
  only:
    - fati
    - main

deploy-backend:
  stage: deploy
  script:
    - az webapp config container set \
      --name $WEBAPP_NAME_BACKEND \
      --resource-group $RESOURCE_GROUP \
      --container-image-name $IMAGE_BACKEND \
      --container-registry-url https://$ACR_LOGIN_SERVER \
      --container-registry-user $ACR_USERNAME \
      --container-registry-password $ACR_PASSWORD
  only:
    - fati
    - main

######################
# FRONTEND PIPELINE
######################

build-frontend:
  stage: build
  script:
    - docker build -t $IMAGE_FRONTEND ./carrental-frontend
  only:
    - fati
    - main

push-frontend:
  stage: push
  script:
    - echo $ACR_PASSWORD | docker login $ACR_LOGIN_SERVER -u $ACR_USERNAME --password-stdin
    - docker push $IMAGE_FRONTEND
  only:
    - fati
    - main

deploy-frontend:
  stage: deploy
  script:
    - az webapp config container set \
      --name $WEBAPP_NAME_FRONTEND \
      --resource-group $RESOURCE_GROUP \
      --container-image-name $IMAGE_FRONTEND \
      --container-registry-url https://$ACR_LOGIN_SERVER \
      --container-registry-user $ACR_USERNAME \
      --container-registry-password $ACR_PASSWORD
  only:
    - fati
    - main

##########################
# CONVERTER PIPELINE
##########################

build-converter:
  stage: build
  script:
    - docker build -t $IMAGE_CONVERTER ./currency_converter
  only:
    - fati
    - main

push-converter:
  stage: push
  script:
    - echo $ACR_PASSWORD | docker login $ACR_LOGIN_SERVER -u $ACR_USERNAME --password-stdin
    - docker push $IMAGE_CONVERTER
  only:
    - fati
    - main

deploy-converter:
  stage: deploy
  script:
    - az webapp config container set \
      --name $WEBAPP_NAME_CONVERTER \
      --resource-group $RESOURCE_GROUP \
      --container-image-name $IMAGE_CONVERTER \
      --container-registry-url https://$ACR_LOGIN_SERVER \
      --container-registry-user $ACR_USERNAME \
      --container-registry-password $ACR_PASSWORD
  only:
    - fati
    - main
