version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - carrental-net

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - carrental-net

  user-service:
    build:
      context: ./carrental-backend/user-service
    ports:
      - "8090:8090"   # DÜZELTİLDİ
    environment:
      SERVER_PORT: 8090   # DÜZELTİLDİ
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/carrental
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - carrental-net

  car-booking-service:
    build:
      context: ./carrental-backend/car-booking-service
    ports:
      - "8100:8100"   # DÜZELTİLDİ
    environment:
      SERVER_PORT: 8100   # DÜZELTİLDİ
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/carrental
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - carrental-net

  currency-converter:
    build:
      context: ./currency_converter
    ports:
      - "50051:50051"
    networks:
      - carrental-net

  frontend:
    build:
      context: ./carrental-frontend
    ports:
      - "3000:3000"
    depends_on:
      - car-booking-service
      - user-service
    networks:
      - carrental-net

volumes:
  mongodb_data:

networks:
  carrental-net:
    driver: bridge
