services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: se-carrental2
      POSTGRES_USER: chef
      POSTGRES_PASSWORD: FH_campus_wien
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - carrental-net

  backend:
    build:
      context: ./carrental
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://se-carrental2.postgres.database.azure.com:5432/postgres?user=chef&password=FH_campus_wien&sslmode=require"
      SPRING_DATASOURCE_USERNAME: chef
      SPRING_DATASOURCE_PASSWORD: FH_campus_wien
      CORS_ALLOWED_ORIGINS: http://localhost:3000,https://carrental-frontend-app.azurewebsites.net
      CURRENCY_CONVERTER_URL: http://currency-converter:80/?wsdl
      CURRENCY_CONVERTER_USERNAME: admin
      CURRENCY_CONVERTER_PASSWORD: master
      AUTH_USERNAME: admin
      AUTH_PASSWORD: master
    restart: on-failure
    networks:
      - carrental-net

  frontend:
    build:
      context: ./carrental-frontend
      args:
        API_BASE_URL: http://localhost:8080/api/v1
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      API_BASE_URL: http://localhost:8080/api/v1
      AUTH_USERNAME: admin
      AUTH_PASSWORD: master
      NODE_ENV: development
    networks:
      - carrental-net

  currency-converter:
    build:
      context: ./currency_converter
    ports:
      - "5000:80"
    environment:
      AUTH_USERNAME: admin
      AUTH_PASSWORD: master
    networks:
      - carrental-net

volumes:
  pgdata:

networks:
  carrental-net:
    driver: bridge
