version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: carrental
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - carrental-net

  backend:
    build:
      context: ./carrental
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/carrental
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
    networks:
      - carrental-net

  frontend:
    build:
      context: ./carrental-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      API_BASE_URL: http://backend:8080
    networks:
      - carrental-net

  currency_converter:
    build:
      context: ./currency_converter
    ports:
      - "5000:80"
    networks:
      - carrental-net

volumes:
  pgdata:

networks:
  carrental-net:
    driver: bridge
