# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/currency_converter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eproto/currency_converter.proto\x12\x11\x63urrencyconverter\"8\n\x11\x43onversionRequest\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x02\x12\x13\n\x0bto_currency\x18\x02 \x01(\t\".\n\x12\x43onversionResponse\x12\x18\n\x10\x63onverted_amount\x18\x01 \x01(\x02\x32u\n\x11\x43urrencyConverter\x12`\n\x0f\x43onvertCurrency\x12$.currencyconverter.ConversionRequest\x1a%.currencyconverter.ConversionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.currency_converter_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CONVERSIONREQUEST']._serialized_start=53
  _globals['_CONVERSIONREQUEST']._serialized_end=109
  _globals['_CONVERSIONRESPONSE']._serialized_start=111
  _globals['_CONVERSIONRESPONSE']._serialized_end=157
  _globals['_CURRENCYCONVERTER']._serialized_start=159
  _globals['_CURRENCYCONVERTER']._serialized_end=276
# @@protoc_insertion_point(module_scope)
