name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_BACKEND: ${{ secrets.ACR_LOGIN_SERVER }}/carrental-backend
      IMAGE_FRONTEND: ${{ secrets.ACR_LOGIN_SERVER }}/carrental-frontend
      IMAGE_CONVERTER: ${{ secrets.ACR_LOGIN_SERVER }}/currency-converter

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Backend
        run: |
          docker build -t $IMAGE_BACKEND ./carrental
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin
          docker push $IMAGE_BACKEND

      - name: Build and Push Frontend
        run: |
          docker build -t $IMAGE_FRONTEND ./carrental-frontend
          docker push $IMAGE_FRONTEND

      - name: Build and Push Converter
        run: |
          docker build -t $IMAGE_CONVERTER ./currency_converter
          docker push $IMAGE_CONVERTER

      - name: Deploy to Azure Web App - Backend
        run: |
          az webapp config container set \
            --name ${{ secrets.WEBAPP_NAME_BACKEND }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --container-image-name $IMAGE_BACKEND \
            --container-registry-url https://${{ secrets.ACR_LOGIN_SERVER }} \
            --container-registry-user ${{ secrets.ACR_USERNAME }} \
            --container-registry-password ${{ secrets.ACR_PASSWORD }}

      - name: Deploy to Azure Web App - Frontend
        run: |
          az webapp config container set \
            --name ${{ secrets.WEBAPP_NAME_FRONTEND }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --container-image-name $IMAGE_FRONTEND \
            --container-registry-url https://${{ secrets.ACR_LOGIN_SERVER }} \
            --container-registry-user ${{ secrets.ACR_USERNAME }} \
            --container-registry-password ${{ secrets.ACR_PASSWORD }}

      - name: Deploy to Azure Web App - Converter
        run: |
          az webapp config container set \
            --name ${{ secrets.WEBAPP_NAME_CONVERTER }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --container-image-name $IMAGE_CONVERTER \
            --container-registry-url https://${{ secrets.ACR_LOGIN_SERVER }} \
            --container-registry-user ${{ secrets.ACR_USERNAME }} \
            --container-registry-password ${{ secrets.ACR_PASSWORD }}
