name: Azure Deployment

on:
  push:
    branches:
      - main

env:
  ACR_LOGIN_SERVER: carrental.azurecr.io
  ACR_USERNAME: carrental
  ACR_PASSWORD: PcVqOtQSd7a9IcuOpJliUF0JbOEOzL98untd2VswXn+ACRCvg1tj
  RESOURCE_GROUP: se-carrental
  WEBAPP_NAME_BACKEND: carrental-backend-app
  WEBAPP_NAME_FRONTEND: carrental-frontend-app
  WEBAPP_NAME_CONVERTER: currency-converter-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Login to Azure Container Registry
        run: |
          echo "$ACR_PASSWORD" | docker login $ACR_LOGIN_SERVER -u $ACR_USERNAME --password-stdin

      - name: Build and push Backend
        run: |
          docker build -t $ACR_LOGIN_SERVER/carrental-backend ./carrental
          docker push $ACR_LOGIN_SERVER/carrental-backend

      - name: Build and push Frontend
        run: |
          docker build -t $ACR_LOGIN_SERVER/carrental-frontend ./carrental-frontend
          docker push $ACR_LOGIN_SERVER/carrental-frontend

      - name: Build and push Currency Converter
        run: |
          docker build -t $ACR_LOGIN_SERVER/currency-converter ./currency_converter
          docker push $ACR_LOGIN_SERVER/currency-converter

      - name: Deploy Backend
        run: |
          az webapp config container set \
            --name $WEBAPP_NAME_BACKEND \
            --resource-group $RESOURCE_GROUP \
            --container-image-name $ACR_LOGIN_SERVER/carrental-backend \
            --container-registry-url https://$ACR_LOGIN_SERVER \
            --container-registry-user $ACR_USERNAME \
            --container-registry-password $ACR_PASSWORD

      - name: Deploy Frontend
        run: |
          az webapp config container set \
            --name $WEBAPP_NAME_FRONTEND \
            --resource-group $RESOURCE_GROUP \
            --container-image-name $ACR_LOGIN_SERVER/carrental-frontend \
            --container-registry-url https://$ACR_LOGIN_SERVER \
            --container-registry-user $ACR_USERNAME \
            --container-registry-password $ACR_PASSWORD

      - name: Deploy Currency Converter
        run: |
          az webapp config container set \
            --name $WEBAPP_NAME_CONVERTER \
            --resource-group $RESOURCE_GROUP \
            --container-image-name $ACR_LOGIN_SERVER/currency-converter \
            --container-registry-url https://$ACR_LOGIN_SERVER \
            --container-registry-user $ACR_USERNAME \
            --container-registry-password $ACR_PASSWORD
