name: Build, Push & Restart Part 2 Services

on:
  push:
    branches:
      - Part-2

env:

  ACR_LOGIN_SERVER: carrental.azurecr.io
  ACR_USERNAME: carrental
  ACR_PASSWORD: PcVqOtQSd7a9IcuOpJliUF0JbOEOzL98untd2VswXn+ACRCvg1tj
  RESTART_BACKEND: https://management.azure.com/subscriptions/xxx/resourceGroups/se-carrental/providers/Microsoft.Web/sites/car-booking-service-app/restart?api-version=2022-03-01
  RESTART_FRONTEND: https://management.azure.com/subscriptions/xxx/resourceGroups/se-carrental/providers/Microsoft.Web/sites/carrental-frontend-part2/restart?api-version=2022-03-01
  RESTART_CONVERTER: https://management.azure.com/subscriptions/xxx/resourceGroups/se-carrental/providers/Microsoft.Web/sites/currency-converter-part2/restart?api-version=2022-03-01

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Docker Login to ACR
        run: echo "$ACR_PASSWORD" | docker login $ACR_LOGIN_SERVER -u $ACR_USERNAME --password-stdin

      - name: Build & Push Car Booking Service
        run: |
          docker build -t $ACR_LOGIN_SERVER/car-booking-service:part2 \
         --file ./carrental-backend/car-booking-service/Dockerfile \
          ./carrental-backend

      - name: Build & Push User Service
        run: |
          docker build -t $ACR_LOGIN_SERVER/user-service:part2 ./carrental-backend/user-service
          docker push $ACR_LOGIN_SERVER/user-service:part2

      - name: Build & Push Frontend
        run: |
          docker build -t $ACR_LOGIN_SERVER/carrental-frontend:part2 ./carrental-frontend
          docker push $ACR_LOGIN_SERVER/carrental-frontend:part2

      - name: Build & Push Currency Converter
        run: |
          docker build -t $ACR_LOGIN_SERVER/currency-converter:part2 ./currency_converter
          docker push $ACR_LOGIN_SERVER/currency-converter:part2

      - name: Restart Backend Web App (Car Booking)
        run: |
          curl -X POST "$RESTART_BACKEND" \
            -H "Authorization: Bearer $AZURE_ACCESS_TOKEN" \
            -H "Content-Length: 0"

      - name: Restart Frontend Web App
        run: |
          curl -X POST "$RESTART_FRONTEND" \
            -H "Authorization: Bearer $AZURE_ACCESS_TOKEN" \
            -H "Content-Length: 0"

      - name: Restart Currency Converter Web App
        run: |
          curl -X POST "$RESTART_CONVERTER" \
            -H "Authorization: Bearer $AZURE_ACCESS_TOKEN" \
            -H "Content-Length: 0"
