name: Azure Deployment

on:
  push:
    branches:
      - main

env:
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
  WEBAPP_NAME_BACKEND: ${{ secrets.WEBAPP_NAME_BACKEND }}
  WEBAPP_NAME_FRONTEND: ${{ secrets.WEBAPP_NAME_FRONTEND }}
  WEBAPP_NAME_CONVERTER: ${{ secrets.WEBAPP_NAME_CONVERTER }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
            registry: ${{ secrets.ACR_LOGIN_SERVER }}
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Backend
        run: |
          docker build -t $ACR_LOGIN_SERVER/carrental-backend ./carrental
          docker push $ACR_LOGIN_SERVER/carrental-backend

      - name: Build and push Frontend
        run: |
          docker build -t $ACR_LOGIN_SERVER/carrental-frontend ./carrental-frontend
          docker push $ACR_LOGIN_SERVER/carrental-frontend

      - name: Build and push Currency Converter
        run: |
          docker build -t $ACR_LOGIN_SERVER/currency-converter ./currency_converter
          docker push $ACR_LOGIN_SERVER/currency-converter

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Backend
        run: |
          az webapp config container set \
            --name $WEBAPP_NAME_BACKEND \
            --resource-group $RESOURCE_GROUP \git 
            --container-image-name $ACR_LOGIN_SERVER/carrental-backend \
            --container-registry-url https://$ACR_LOGIN_SERVER \
            --container-registry-user $ACR_USERNAME \
            --container-registry-password $ACR_PASSWORD

      - name: Deploy Frontend
        run: |
          az webapp config container set \
            --name $WEBAPP_NAME_FRONTEND \
            --resource-group $RESOURCE_GROUP \
            --container-image-name $ACR_LOGIN_SERVER/carrental-frontend \
            --container-registry-url https://$ACR_LOGIN_SERVER \
            --container-registry-user $ACR_USERNAME \
            --container-registry-password $ACR_PASSWORD

      - name: Deploy Currency Converter
        run: |
          az webapp config container set \
            --name $WEBAPP_NAME_CONVERTER \
            --resource-group $RESOURCE_GROUP \
            --container-image-name $ACR_LOGIN_SERVER/currency-converter \
            --container-registry-url https://$ACR_LOGIN_SERVER \
            --container-registry-user $ACR_USERNAME \
            --container-registry-password $ACR_PASSWORD
